name: "Run Python Script"
description: "SVGファイルを添付してワークフローを実行します"
title: "Run script"
labels: ["automation"]
body:
  - type: input
    id: note
    attributes:
      label: "備考"
      description: "任意でコメントを入力してください"
      placeholder: "例: ロゴv2"
    validations:
      required: false

  - type: markdown
    attributes:
      value: "ここに **.svg ファイル** をドラッグ＆ドロップして添付してください。"
