name: "Run Python Script"
description: "SVG文字列を入力して処理します"
title: "Run script"
labels: ["automation"]
body:
  - type: textarea
    id: svg_text
    attributes:
      label: "a"
      description: "ここにSVGファイルの中身を直接貼り付けてください"
      placeholder: "<svg>...</svg>"
    validations:
      required: true
